# Generated by Django 6.0.2 on 2026-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=60)),
                ('categorie', models.CharField(max_length=60)),
                ('tempspreparation', models.IntegerField()),
                ('imagpath', models.TextField(max_length=300)),
            ],
        ),
    ]
